#docker build . -t ethereum:alpine
FROM alpine:3.8


# Update
RUN apk update
RUN apk add --no-cache binutils-gold \
        curl \
        g++ \
        gcc \
        gnupg \
        libgcc \
        linux-headers \
        make \
        python 

        

RUN mkdir -p /opt/nodejs \
    && cd /opt/nodejs \
    && wget http://nodejs.org/dist/v12.18.1/node-v12.18.1.tar.gz \
    && tar -zxvf node-v12.18.1.tar.gz \
    && mv node-v12.18.1 node \
    && cd node \
    && ./configure \
    && make -j4 \
    && make install
    

RUN npm -g install npm@latest-2

RUN npm install -g truffle

EXPOSE 3000 3001